/* ─── Config ─────────────────────────────────────────────── */
// Replace with your OpenWeatherMap API key
// Get one free at https://openweathermap.org/api
const API_KEY = '826a16bbb524239f564337ec45f9a08c';
const BASE_URL = 'https://api.openweathermap.org/data/2.5/weather';

/* ─── Slot detection ─────────────────────────────────────── */
// The SLOT env var is injected at build/deploy time via a
// config.js file (generated by the Docker entrypoint).
// Falls back to 'blue' if not set.
const SLOT = window.APP_SLOT || 'blue';
const VERSION = window.APP_VERSION || '1.0.0';

document.getElementById('slotBadge').textContent = SLOT.toUpperCase();
document.getElementById('appVersion').textContent = VERSION;

if (SLOT === 'green') {
  document.body.classList.add('slot-green');
}

/* ─── State ──────────────────────────────────────────────── */
let currentUnit = 'C';
let lastData = null;

/* ─── Weather icons map ──────────────────────────────────── */
const iconMap = {
  '01d': '☀️', '01n': '🌙',
  '02d': '🌤', '02n': '🌤',
  '03d': '⛅', '03n': '⛅',
  '04d': '☁️', '04n': '☁️',
  '09d': '🌧', '09n': '🌧',
  '10d': '🌦', '10n': '🌦',
  '11d': '⛈', '11n': '⛈',
  '13d': '❄️', '13n': '❄️',
  '50d': '🌫', '50n': '🌫',
};

/* ─── Fetch weather ──────────────────────────────────────── */
async function fetchWeather(city) {
  clearError();
  if (!city.trim()) { showError('Please enter a city name.'); return; }

  try {
    const url = `${BASE_URL}?q=${encodeURIComponent(city)}&appid=${API_KEY}&units=metric`;
    const res = await fetch(url);
    if (!res.ok) {
      if (res.status === 404) showError(`City "${city}" not found.`);
      else if (res.status === 401) showError('Invalid API key — see app.js to configure.');
      else showError(`Error ${res.status}: please try again.`);
      return;
    }
    const data = await res.json();
    lastData = data;
    renderWeather(data);
  } catch (e) {
    // Demo mode if no API key set
    if (API_KEY === '826a16bbb524239f564337ec45f9a08c') {
      renderDemo(city);
    } else {
      showError('Network error. Check your connection.');
    }
  }
}

/* ─── Render ─────────────────────────────────────────────── */
function renderWeather(data) {
  const card = document.getElementById('weatherCard');
  card.style.animation = 'none';
  card.offsetHeight; // reflow
  card.style.animation = '';

  document.getElementById('cityName').textContent = data.name;
  document.getElementById('countryName').textContent =
    `${data.sys.country} · ${new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'short', day: 'numeric' })}`;

  const icon = data.weather[0].icon;
  document.getElementById('weatherIcon').textContent = iconMap[icon] || '🌡';
  document.getElementById('conditionText').textContent = data.weather[0].description;

  updateTemp(data.main.temp, data.main.feels_like);
  document.getElementById('humidity').textContent = `${data.main.humidity}%`;
  document.getElementById('wind').textContent = `${Math.round(data.wind.speed * 3.6)} km/h`;
  document.getElementById('visibility').textContent = `${(data.visibility / 1000).toFixed(1)} km`;
}

function updateTemp(tempC, feelsC) {
  if (currentUnit === 'C') {
    document.getElementById('tempVal').textContent = `${Math.round(tempC)}°`;
    document.getElementById('feelsLike').textContent = `${Math.round(feelsC)}°`;
  } else {
    document.getElementById('tempVal').textContent = `${Math.round(tempC * 9/5 + 32)}°`;
    document.getElementById('feelsLike').textContent = `${Math.round(feelsC * 9/5 + 32)}°`;
  }
}

/* ─── Demo mode (no API key) ─────────────────────────────── */
function renderDemo(city) {
  lastData = {
    name: city || 'Mumbai',
    sys: { country: 'IN' },
    weather: [{ icon: '02d', description: 'partly cloudy' }],
    main: { temp: 31, feels_like: 34, humidity: 72 },
    wind: { speed: 4.2 },
    visibility: 8000,
  };
  renderWeather(lastData);
  showError('Demo mode — add your OpenWeatherMap API key in app.js');
}

/* ─── Unit toggle ────────────────────────────────────────── */
function switchUnit(unit) {
  currentUnit = unit;
  document.getElementById('btnC').classList.toggle('active', unit === 'C');
  document.getElementById('btnF').classList.toggle('active', unit === 'F');
  if (lastData) {
    updateTemp(lastData.main.temp, lastData.main.feels_like);
  }
}

/* ─── Error helpers ──────────────────────────────────────── */
function showError(msg) { document.getElementById('errorMsg').textContent = msg; }
function clearError() { document.getElementById('errorMsg').textContent = ''; }

/* ─── Event listeners ────────────────────────────────────── */
document.getElementById('searchBtn').addEventListener('click', () => {
  fetchWeather(document.getElementById('cityInput').value);
});

document.getElementById('cityInput').addEventListener('keydown', (e) => {
  if (e.key === 'Enter') fetchWeather(e.target.value);
});

/* ─── Init — load default city ───────────────────────────── */
window.addEventListener('DOMContentLoaded', () => {
  fetchWeather('London');
});
