apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: weather-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "Blue-Green deployment for Weather App"
  sourceRepos:
    - "https://github.com/avadhutpatil22/Argo-CD/weather-app-gitops.git"
  destinations:
    - namespace: weather-app
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "apps"
      kind: Deployment
    - group: ""
      kind: Service
