apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: my-app

resources:
  - ../../base


nameSuffix: -blue

patches:
  # Override the slot label on the Pod template
  - patch: |-
      - op: replace
        path: /spec/template/metadata/labels/slot
        value: blue
      - op: replace
        path: /metadata/name
        value: my-app-blue
    target:
      kind: Deployment
      name: my-app

images:
  - name: nginx
    newTag: "1.25.0"   # pin the STABLE image for the blue slot
