apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app
  namespace: weather-app
  labels:
    app: weather-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        app: weather-app
        slot: blue          # overridden per overlay
    spec:
      containers:
        - name: weather-app
          image: ghcr.io/https://github.com/avadhutpatil22/Argo-CD/weather-app:latest   # update this
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 150m
              memory: 128Mi
